// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	Createtransfer(ctx context.Context, arg CreatetransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeletedEntry(ctx context.Context, id int64) error
	Deletetransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetAccounts(ctx context.Context, arg GetAccountsParams) ([]Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetUser(ctx context.Context, name string) (User, error)
	GeteEtries(ctx context.Context, arg GeteEtriesParams) ([]Entry, error)
	Gettransfer(ctx context.Context, id int64) (Transfer, error)
	Gettransfers(ctx context.Context, arg GettransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountByBalance(ctx context.Context, arg UpdateAccountByBalanceParams) (Account, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error)
	Updatetransfer(ctx context.Context, arg UpdatetransferParams) (Transfer, error)
}

var _ Querier = (*Queries)(nil)
