// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name,
  password,
  full_name,
  email
) VALUES (
  $1, $2, $3, $4
)
RETURNING name, password, full_name, email, password_change_at, create_at
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Password,
		arg.FullName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.Name,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.PasswordChangeAt,
		&i.CreateAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT name, password, full_name, email, password_change_at, create_at FROM users
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.Name,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.PasswordChangeAt,
		&i.CreateAt,
	)
	return i, err
}
